### ISSUE TITLE
Display products as seen in wireframes

### ISSUE THREAD

**Issue by uncletammy** [AshleyMSherwood/cuntSoap#3]
As a website guest, I want be able to browse the products available including a photo and description of each.  The products should appear as they do in the wireframes.

**Comment by uncletammy** [comment]
Dummy data for products has been exposed on an array called `uiProducts` on the scope of `assets/js/controllers/brochure/ProductsCtrl.js`

**Comment by uncletammy** [comment]
Each product on the products page should be contained in a box where the product image is displayed as the background of the box (using the css "background-image" attribute) and the product title is overlaying the image.  When you mouseOver the box, it should go from displaying the title only to displaying the title and the product description.

**Comment by uncletammy** [comment]
We talked about just showing the description onClick instead of onMouseover but I changed my mind. 

When you mouseover a product, I'd like the product title to slide from the bottom of the box to the top of the box.  This should reveal the product description and also the charity that the product goes to (in the same container as the product title).  

You should be able to accomplish this by setting a fixed position on the container that holds the product title and setting a css `top` value to make the container show up at the bottom of the product box.  You will also need to use the css psuedo-class `:hover` to change `top` attribute which will move the title to the top.  You can use css transitions to make it slide.

**Comment by AshleyMSherwood** [comment]
Done!  Beautiful!  Amaze!
