### ISSUE TITLE
Remove links on left pulldown menu

### ISSUE THREAD

**Issue by uncletammy** [AshleyMSherwood/cuntSoap#5]
The pulldown menu on the left should be for general site navigation.  The pulldown on the right should be for things related to a user and their account.  

Because of this, I feel like the `log in` and `signup` links should only be in the right pulldown.  Please remove those two links from the left pulldown.

**Comment by AshleyMSherwood** [comment]
Done!  Also added "logout" button on right pull-down menu when you're logged in.
