### ISSUE TITLE
Redesign landing page

### ISSUE THREAD

**Issue by uncletammy** [AshleyMSherwood/cuntSoap#6]
The landing page (homepage, whatever) is pretty sloppy.  I would like it to briefly describe what cunt is and also have an input field where you can sign up for a waitlist.   

Feel free to use placeholder text and I will put in the actual copy at a later date.  This issue will require you to do some design work.  Look at other people's waitlist landing pages as a guide.

**Comment by AshleyMSherwood** [comment]
Done :8ball:
